@echo off
echo Starting GlobeTrotter Backend...
cd server
echo Installing ALL dependencies...
call npm install prisma@5.22.0 @prisma/client@5.22.0 bcryptjs jsonwebtoken cors dotenv express --save
echo Setting up Database...
call npx prisma db push --accept-data-loss
echo Starting Server...
node index.js
pause
